export * as Auth from "./auth";
export * as Settings from "./settings";
export * as Hospitals from "./hospital";
export { default as HomePage } from "./home/home";
export { default as UserPanel } from "./userPanale/userPanel";
export { default as DoctorPage } from "./doctors/doctor";
export { default as Spetialization } from "./spetialization/spetialization";
export { default as Booking } from "./booking/booking";
export { default as SingleBooking } from "./booking/single-booking";
export { default as Page404 } from "./404/404"; 